export const sliderArray = [
    {
        id: 1,
        title:  'Rice from India',
        description: 'very delicious rice',
        picture: '/m-classic-ribe-risotto.jpg',
        price: '20$',
        weight: 'kg',
        x: 23,
        y: 145,
    },
    {
        id: 2,
        title:  'Suessmanda',
        description: 'interestiong marsilllais',
        picture: '/le-petit-marseillais-festseife-suessmande.jpg',
        price: '23$',
        weight: 'kg',
        x: 230,
        y: 45,
    },
    {
        id: 3,
        title:  'Amazing potz',
        description: 'very delicious Potz',
        picture: '/potz-potz-xpert-javel-multi-cleaner.jpg',
        price: '10$',
        weight: 'kg',
        x: 230,
        y: 245,
    },
    {
        id: 4,
        title:  'Rice from India',
        description: 'very delicious rice',
        picture: '/m-classic-ribe-risotto.jpg',
        price: '20$',
        weight: 'kg',
        x: 123,
        y: 185,
    },
    {
        id: 5,
        title:  'Suessmanda',
        description: 'interestiong marsilllais',
        picture: '/le-petit-marseillais-festseife-suessmande.jpg',
        price: '23$',
        weight: 'kg',
        x: 323,
        y: 245,
    },
    


];