import Link from "next/link";
import Head from "next/head";
import HotSpot from "../components/HotSpot";

export default function Home() {
  
  return (
    <>
      <Head>
        <title>oh hello how nice!</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <HotSpot/>
    </>
  );
}
